# Generated by Django 5.2.12 on 2026-03-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoAvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('priority', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('applies_to', models.CharField(default='All Providers', max_length=100)),
                ('conditions', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Availability Rule',
                'verbose_name_plural': 'Availability Rules',
                'db_table': 'availability_rules',
                'ordering': ['priority', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoPtoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='FastAPI ID')),
                ('user_ext_id', models.CharField(blank=True, max_length=36, verbose_name='Provider FastAPI ID')),
                ('provider_name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('PTO', 'PTO'), ('Sick', 'Sick Leave'), ('Conference', 'Conference'), ('Blocked', 'Blocked Time')], default='PTO', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('date_from', models.CharField(max_length=20)),
                ('date_to', models.CharField(max_length=20)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('coverage_provider', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PTO / Leave Request',
                'verbose_name_plural': 'PTO / Leave Requests',
                'db_table': 'pto_requests',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, choices=[('General', 'General'), ('Procedure', 'Procedure'), ('Specialty', 'Specialty'), ('Consult', 'Consult'), ('Diagnostic', 'Diagnostic')], max_length=50)),
                ('icon', models.CharField(default='fa-door-open', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('badge', models.CharField(default='Provider', max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('days', models.CharField(blank=True, max_length=100)),
                ('hours', models.CharField(blank=True, max_length=100)),
                ('types', models.CharField(blank=True, max_length=255)),
                ('applied_to', models.CharField(blank=True, max_length=255)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Schedule Template',
                'verbose_name_plural': 'Schedule Templates',
                'db_table': 'schedule_templates',
                'ordering': ['name'],
                'managed': False,
            },
        ),
    ]
